FROM node:20-alpine@sha256:afdf98210b07b586eb71fa22ba2e432e058e4cd1304d31ed60888755b8c865fb

RUN apk add --no-cache libc6-compat

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED 1
ENV WATCHPACK_POLLING true

EXPOSE 3000

CMD ["sh", "-c", "npm install && npm run dev"]
