apiVersion: v1
kind: Namespace
metadata:
  name: mathsmania
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: mathsmania
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: mathsmania-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: mathsmania
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: mathsmania-frontend
