import { pgTable, uuid, varchar, text, integer, doublePrecision, boolean, timestamp, jsonb, index, uniqueIndex, primaryKey } from 'drizzle-orm/pg-core';
import { users } from './users';

export const typingTests = pgTable('typing_tests', {
  id: uuid('id').notNull(),
  userId: uuid('user_id').references(() => users.id).notNull(),
  passageId: uuid('passage_id'),
  mode: varchar('mode', { length: 50 }).notNull(),
  status: varchar('status', { length: 20 }).default('completed').notNull(),
  durationSeconds: integer('duration_seconds').notNull(),
  timeTakenSeconds: doublePrecision('time_taken_seconds'),
  timeUtilizationPercentage: doublePrecision('time_utilization_percentage'),
  typedContent: text('typed_content'),
  originalContent: text('original_content'),
  grossWpm: doublePrecision('gross_wpm'),
  netWpm: doublePrecision('net_wpm'),
  accuracy: doublePrecision('accuracy'),
  errorPercentage: doublePrecision('error_percentage'),
  keyDepressionCount: integer('key_depression_count'),
  correctKeyDepressions: integer('correct_key_depressions'),
  incorrectKeyDepressions: integer('incorrect_key_depressions'),
  omissionErrors: integer('omission_errors'),
  additionErrors: integer('addition_errors'),
  wrongWordErrors: integer('wrong_word_errors'),
  substitutionErrors: integer('substitution_errors'),
  formattingErrors: integer('formatting_errors'),
  spaceErrors: integer('space_errors'),
  fullMistakes: integer('full_mistakes'),
  halfMistakes: integer('half_mistakes'),
  totalErrors: integer('total_errors'),
  totalWordsTyped: integer('total_words_typed'),
  totalCorrectWords: integer('total_correct_words'),
  backspaceCount: integer('backspace_count'),
  pauseCount: integer('pause_count'),
  totalPauseDurationSeconds: doublePrecision('total_pause_duration_seconds'),
  avgPauseDuration: doublePrecision('avg_pause_duration'),
  longestPauseDuration: doublePrecision('longest_pause_duration'),
  typingRhythmScore: doublePrecision('typing_rhythm_score'),
  consistencyScore: doublePrecision('consistency_score'),
  isQualified: boolean('is_qualified'),
  qualificationProbability: doublePrecision('qualification_probability'),
  keystrokeSummary: jsonb('keystroke_summary'),
  errorZones: jsonb('error_zones'),
  weakWords: jsonb('weak_words'),
  xpEarned: integer('xp_earned').default(0).notNull(),
  isPremium: boolean('is_premium').default(false).notNull(),
  trustScore: integer('trust_score').default(100).notNull(),
  idempotencyKey: varchar('idempotency_key', { length: 255 }).notNull(),
  startedAt: timestamp('started_at'),
  completedAt: timestamp('completed_at'),
  createdAt: timestamp('created_at').notNull(),
}, (table) => {
  return {
    pk: primaryKey({ columns: [table.id, table.createdAt] }),
    userIdIdx: index('user_id_idx').on(table.userId),
    idempotencyIdx: uniqueIndex('idempotency_idx').on(table.idempotencyKey, table.createdAt),
  };
});
